wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    mask/class_labels:
      predictions_wandb_delimeter_ground truth:
        key: predictions_wandb_delimeter_ground truth
        type: mask/class_labels
        value:
          '0': endpoint
          '1': biffurcation
          '2': crossing
      predictions_wandb_delimeter_prediction:
        key: predictions_wandb_delimeter_prediction
        type: mask/class_labels
        value:
          '0': endpoint
          '1': biffurcation
          '2': crossing
    python_version: 3.8.9
    start_time: 1642028293
    t:
      1:
      - 1
      - 9
      2:
      - 1
      - 9
      4: 3.8.9
      5: 0.12.9
      8:
      - 5
